# Generated by Django 3.2.6 on 2022-01-29 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77bbe03c-0615-415a-a48e-85879e65b1df'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ac01e7ca-dbc9-4855-9e80-5dd7ea0a9155'), primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('one_mes', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
