# Generated by Django 3.2.6 on 2022-01-29 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220129_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef2f3deb-4fe8-4f71-9922-48e0a84fb791'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77b78965-3f1d-4f47-b790-aacfa0e4c082'), primary_key=True, serialize=False),
        ),
    ]
