# Generated by Django 3.2.6 on 2022-01-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220129_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b97f7401-933c-4932-ae45-58bf690727dd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6130a05b-6007-4494-a99a-ad7dbac37e16'), primary_key=True, serialize=False),
        ),
    ]
