# Generated by Django 3.2.6 on 2022-01-29 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220129_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7a5de95-6dd7-4455-a3c5-a1427b3c6e56'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9955ae25-1fa4-4357-9d81-5bdeb796fae2'), primary_key=True, serialize=False),
        ),
    ]
