# Generated by Django 3.2.6 on 2022-01-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('66976fb8-8861-408a-ac79-3ec39a633e18'), primary_key=True, serialize=False)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_send_from', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
