# Generated by Django 3.2.6 on 2022-01-30 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='deny_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='promise_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bc2f5bb-cfb8-4733-9ae1-7f1d4c1b2076'), primary_key=True, serialize=False),
        ),
    ]
