# Generated by Django 3.2.6 on 2022-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='images/unknown.jpeg', null=True, upload_to='images/'),
        ),
    ]
