# Generated by Django 3.2.6 on 2022-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220218_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='images/unknown.jpeg', null=True, upload_to='../media/images/'),
        ),
    ]
