# Generated by Django 3.2.6 on 2022-02-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='one_mes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
